export const cv = {
  name: "Jehona",
  surname: "Rrahmani",
  image_url: "/images/jehona.jpg",
  email: "jehonarrahmani061@gmail.com",
  birthday: "27/11/1997",
  phone_number: "+383 49 588 917",
  address: "10000 Prishtinë, Kosovë",
  role: "Finance and Accountant Assistant",
  description_of_me:
    "As a Finance Assistant, my goal is to support organizations in achieving their financial objectives. With a strong foundation in financial analysis, budgeting, and risk management, I am dedicated to optimizing financial processes and providing actionable insights. <br/> In my role as an Accountant Assistant, I am passionate about maintaining the financial health of organizations. I excel in tasks such as data entry, reconciliations, and financial record-keeping.",
  experience: [
    {
      from: "12/2023",
      to: "Current",
      company_name: "Digitnest LLC",
      your_role: "Bookkeeper",
      your_responsibilities: [
        "Assisted in the preparation of financial statements, income statements, and balance sheets.",
        "Conducted data entry and maintained accurate financial records.",
        "Supported the month-end and year-end closing processes.",
        "Assisted with accounts payable and accounts receivable tasks.",
        "Conducted bank reconciliations to ensure accuracy of financial data.",
        "Collaborated with the accounting team to resolve discrepancies and errors.",
        "Contributed to budgeting and forecasting activities.",
      ],
    },
    {
      from: "09/2022",
      to: "10/2023",
      company_name: "Provit ShPK",
      your_role: "Account Assistant",
      your_responsibilities: [
        "Recorded financial transactions accurately.",
        "Maintained the general ledger.",
        "Reconciled bank statements and accounts.",
        "Processed invoices, payments, and expense reports.",
        "Managed accounts receivable and payable.",
        "Prepared monthly and annual financial reports.",
        "Assisted with payroll processing.",
        "Ensured compliance with financial regulations.",
        "Supported tax preparation and filing.",
        "Monitored and reported financial discrepancies.",
      ],
    },
    {
      from: "06/2021",
      to: "05/2022",
      company_name: "GSM ShPK",
      your_role: "Finance Manager",
      your_responsibilities: [
        "Led financial analysis efforts to support decision-making and strategic planning.",
        "Managed budgeting and forecasting processes, ensuring alignment with organizational goals.",
        "Conducted in-depth financial research and analysis to identify investment opportunities and risks.",
        "Collaborated with cross-functional teams to optimize capital allocation.",
        "Developed and monitored key performance indicators (KPIs) to track financial performance.",
        "Implemented risk management strategies to safeguard financial assets.",
        "Assisted in the preparation of financial reports for senior management and external stakeholders.",
      ],
    },
  ],
  education: [
    {
      from: "02/2023",
      to: "Current",
      college_name: "IKAF",
      education_title: "Certified accountant",
      degree: "Certified accountant",
    },
    {
      from: "09/2022",
      to: "02/2023",
      college_name: "IKAF",
      education_title: "Accounting technician",
      degree: "Accounting technician",
    },
    {
      from: "10/2017",
      to: "09/2021",
      college_name: "UP 'Hasan Prishtina'",
      education_title: "Accounting and Finance",
      degree: "Bachelor",
    },
  ],
  languages: [
    { name: "English", level: "Advanced" },
    { name: "Albanian", level: "Native" },
  ],
  skills: [
    "Account Management",
    "Financial Reporting",
    "Financial Accounting",
    "Financial Analysis",
    "Cash Flow",
    "Banking",
    "Bookkeeping",
    "Cost Accounting",
    "Accounts Receivable (AR)",
    "Accounts Payable (AP)",
  ],
};
