export const cv = {
  name: "Besjan",
  surname: "Hallaqi",
  image_url: "/images/me.jpg",
  email: "besjan_hallaqi@hotmail.com",
  website_url: "besjanhallaqi.com",
  birthday: "18/06/1999",
  phone_number: "+383 49 840 037",
  address: "12000 Fushë Kosovë, Kosovë",
  role: "Front-end developer",
  description_of_me:
    "Passionate Front-End Developer with expertise in React.js, dedicated to creating responsive and user-friendly web applications. Proficient in modern web technologies, I blend creativity and technical prowess to deliver engaging digital experiences. Committed to continuous learning and collaboration with cross-functional teams to drive innovation in web development.",
  experience: [
    {
      from: "05/2025",
      to: "Current",
      company_name: "hellocare.ai",
      your_role: "Front-end developer",
      your_responsibilities: [
        "Developing scalable and maintainable applications using React and TypeScript",
        "Implementing responsive UI components with CSS Modules and SCSS for better styling control",
        "Building reusable components and hooks to ensure consistency and code reusability",
        "Collaborating closely with cross-functional teams in an Agile development process",
        "Participating in sprint planning, code reviews, and feature discussions",
        "Troubleshooting and resolving UI issues across various devices and browsers",
      ],
    },
    {
      from: "03/2024",
      to: "04/2025",
      company_name: "Visiar HealthCare",
      your_role: "Front-end developer",
      your_responsibilities: [
        "Working with ReactJS, NextJS, TypeScript and TailwindCSS for better user experience",
        "Creating scalable applications",
        "Collaboration with team",
        "Working with Scrum",
        "Managing successful sprints",
        "Finding solutions for a different variations of website problems",
      ],
    },
    {
      from: "02/2023",
      to: "03/2024",
      company_name: "Axians Kosovo",
      your_role: "React developer",
      your_responsibilities: [
        "Working with ReactJS, TypeScript and Material UI for better user experience",
        "Creating and testing applications",
        "Collaboration with team",
        "Working with Scrum",
        "Managing successful sprints",
        "Finding solutions for a different variations of website problems",
        "Maintaining and updating websites",
      ],
    },
    {
      from: "10/2021",
      to: "12/2022",
      company_name: "Sponex L.L.C.",
      your_role: "Front-end developer",
      your_responsibilities: [
        "Proficient in HTML, CSS, TailwindCSS, ReactJS, NextJS, TypeScript, and other relevant web design coding languages",
        "Creating and testing applications for websites",
        "Collaboration with team",
        "Working with graphics and other designers",
        "Finding solutions for a different variations of website problems",
        "Maintaining and updating websites",
        "Staying up-to-date on technology",
      ],
    },
    {
      from: "07/2020",
      to: "10/2020",
      company_name: "ProCredit Bank",
      your_role: "Intern",
      your_responsibilities: [
        "Finished Internship for MIS department in bank",
        "Created reports from database to the all departments in the bank",
        "Used queries in MSSQL for generating reports",
      ],
    },
  ],
  education: [
    {
      from: "09/2017",
      to: "08/2023",
      college_name: "University of Business and Technology",
      education_title: "Computer Science and Engineering",
      degree: "Bachelor",
    },
  ],
  languages: [
    { name: "English", level: "Advanced" },
    { name: "Albanian", level: "Native" },
  ],
  skills: [
    "ReactJS",
    "TypeScript",
    "NextJS",
    "ThreeJS",
    "JavaScript",
    "TailwindCSS",
    "MaterialUI",
    "WordPress",
    "HTML",
    "CSS",
  ],
};
